spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  cloud:
    gateway:
      routes:
        - id: microservice-commande
          uri: lb://AbdaouiSindaCommande
          predicates:
            - Path=/commande/**
          filters:
            - RewritePath=/commande/(?<path>.*) , /${path}
        - id: microservice-transaction
          uri: lb://AbdaouiSindaGestionPaiement
          predicates:
            - Path=/transaction/**
          filters:
            - RewritePath=/transaction/(?<path>.*) , /${path}
